### ISSUE TITLE
Update release to support bionic stemcell

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/cg-awslogs-boshrelease#46]
In order to use bionic stemcells we need to fix this release to support compilation on bionic

## Acceptance Criteria
* Adjust the release to support both xenial and bionic stemcells so it compiles and ships logs to AWS as intended.

## Security considerations
?

See https://docs.google.com/document/d/1zha2C2zhwc4BUozLHcLsHOGNVcJvJGuDorKIlBZ32ms/edit for error messages at compilation time

**Comment by soutenniza** [comment]
https://github.com/alphagov/paas-awslogs-boshrelease has bionic support!

**Comment by ccostino** [comment]
We started working on this today and basing some of the work off of the PR that we received: https://github.com/cloud-gov/cg-awslogs-boshrelease/pull/47

We've had initial success with this, thank you @ChrisMcGowan!  There's more to be done here, which we'll capture in a separate parent ticket.  I'll also follow up in the PR itself to let folks know we're actively looking at it and testing.

**Comment by ChrisMcGowan** [comment]
PR in place https://github.com/cloud-gov/cg-deploy-bosh/pull/446
